In [1]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
#Create a vector with values ranging from 10 to 49
import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#Reverse a vector
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)


Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


In [4]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)

print(non_zero_indices)


(array([0, 1, 4], dtype=int32),)


In [6]:
#Create a 3x3x3 array with random values
import numpy as np

random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.60828939 0.3070207  0.31900073]
  [0.24471968 0.8053685  0.4699416 ]
  [0.03481102 0.5521471  0.97881527]]

 [[0.62138665 0.77952604 0.1202525 ]
  [0.43165146 0.80185671 0.04564249]
  [0.72404355 0.12696697 0.40731649]]

 [[0.07968503 0.07618812 0.25705229]
  [0.79851779 0.68027105 0.85592057]
  [0.41224922 0.76022443 0.47849429]]]


In [7]:
#Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np

random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.26036888 0.31997801 0.72433813 0.80619135 0.242479   0.55891898
  0.66909752 0.09709439 0.9948891  0.22061805]
 [0.15104232 0.08949768 0.02634956 0.84442308 0.99927217 0.32221766
  0.72613746 0.4225548  0.36167922 0.37114418]
 [0.31158059 0.29849566 0.21648751 0.86982329 0.37321051 0.72534979
  0.03750186 0.02214876 0.43998477 0.72709311]
 [0.7512096  0.96488512 0.88914181 0.82863021 0.85230494 0.56314528
  0.12096165 0.35187926 0.64102001 0.22482803]
 [0.97351937 0.96324424 0.73759638 0.09315506 0.30829298 0.73761139
  0.55515018 0.99193064 0.03518075 0.35640529]
 [0.43968753 0.11474391 0.82848296 0.98702405 0.60614394 0.64894657
  0.49628545 0.54248285 0.07301535 0.18893971]
 [0.32781019 0.61685365 0.8953042  0.99525368 0.16246416 0.09723824
  0.79497156 0.23908057 0.37896104 0.71617629]
 [0.11095149 0.62781289 0.85408906 0.8541371  0.05756764 0.70151289
  0.91760992 0.38113308 0.36294205 0.08973024]
 [0.91760008 0.45447931 0.75363426 0.26771259 0.45570178 0.5481979

In [8]:
#Create a 2d array with 1 on the border and 0 inside
import numpy as np

rows = 5
cols = 5

array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Leftmost column
array[:, -1] = 1  # Rightmost column

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
